### ISSUE TITLE
Generic generated wrong JSON adapter

### ISSUE THREAD

**Issue by kevin70** [avaje/avaje-jsonb#39]
```
/**
 * 分页结果对象.
 * @author ZY (kzou227@qq.com)
 */
@Getter
@Setter
@Json(naming = Json.Naming.LowerUnderscore)
public class PageResult<ITEM> {

    /**
     * 页码.
     */
    private int page;
    /**
     * 每页的数量.
     */
    private int pageSize;
    /**
     * 总数量.
     */
    private int totalCount;
    /**
     * 总页数量.
     */
    private int totalPageCount;
    /**
     * 数据项.
     */
    private List<? extends ITEM> items;
}
```

Generated：
```
@Generated
public final class PageResultJsonAdapter extends JsonAdapter<PageResult> implements ViewBuilderAware {

  // naming convention LowerUnderscore
  // page [int] name:page setter:setPage 
  // pageSize [int] name:page_size setter:setPageSize 
  // totalCount [int] name:total_count setter:setTotalCount 
  // totalPageCount [int] name:total_page_count setter:setTotalPageCount 
  // items [java.util.List<? extends ITEM>] name:items setter:setItems 

  private final JsonAdapter<Integer> pintJsonAdapter;
  private final JsonAdapter<List<ITEM>> listITEMJsonAdapter;
  private final PropertyNames names;

  public PageResultJsonAdapter(Jsonb jsonb) {
    this.pintJsonAdapter = jsonb.adapter(Integer.TYPE);
    this.listITEMJsonAdapter = jsonb.adapter(Types.listOf(? extends ITEM.class));
    this.names = jsonb.properties("page", "page_size", "total_count", "total_page_count", "items");
  }

  // ...
 // ...
}
```

`private final JsonAdapter<List<ITEM>> listITEMJsonAdapter;` Compilation will report an error.

**Comment by SentryMan** [comment]
This library can only serialize/deserialize types annotated with `@Json` or imported by `@Json.Import`. Wildcards fulfill neither of these conditions.

**Comment by rbygrave** [comment]
Hmm, I wonder ... it looks possible in the toJson direction by treating the
wildcard type as Object.class.  so List<Object> (which would mean the type
is determined at runtime).

I might try and see if that is possible and if so then it's a question of
whether it's a good idea or not.

**Comment by rbygrave** [comment]
Ok, turns out we can support this and quite nicely.  As a side point, one nice thing about code generation is that for example extra complexity goes into the code generation side of things and (like in this case) basically no extra complexity in the runtime.

Anyway, how this works.

Example:
```java
@Json
public class MyGenericPageResult<T> {

  int page;
  int pageSize;
  int totalPageCount;
  List<? extends T> results;
```

With a generic type like 'MyGenericPageResult<T>' there are 2 ways to use it:
A) With `Object.class` as the type used for the generic type
B) With a specific type like say `Customer.class` where we know the generic type is a specific type like Customer.class.



### 2 constructors

The generated code know that this type has a generic type parameter and creates 2 constructors. One defaults to use `Object.class` and the other to _whatever type parameter we specify_

```java
  public MyGenericPageResultJsonAdapter(Jsonb jsonb, Type param0) {
    this.pintJsonAdapter = jsonb.adapter(Integer.TYPE);
    this.listJsonAdapterGeneric = jsonb.adapter(Types.listOf(param0));             // <!-- HERE !!!!
    this.names = jsonb.properties("page", "pageSize", "totalPageCount", "results");
  }

  /**
   * Construct using Object for generic type parameters.
   */
  public MyGenericPageResultJsonAdapter(Jsonb jsonb) {
    this(jsonb, Object.class);       // <!-- HERE !!!! using Object.class as default type parameter
  }
```

### An extra JsonAdapter.Factory

The generated code also generates an extra JsonAdapter.Factory like:

```java
  public static final JsonAdapter.Factory Factory = (type, jsonb) -> {
    if (type instanceof ParameterizedType && Types.rawType(type) == MyGenericPageResult.class) {
      Type[] args = Types.typeArguments(type);
      return new MyGenericPageResultJsonAdapter(jsonb, args[0]);
    }
    return null;
  };
```
This means that we will be able to use this factory if we use a parameterized type like:

```
Type pageResultAddressType = Types.newParameterizedType(MyGenericPageResult.class, Address.class);

JsonType<MyGenericPageResult<Address>> type = jsonb.type(pageResultAddressType);

```
-----------
The result is that there are 2 ways of using the MyGenericPageResultJsonAdapter.
### 1. Using it with Object.class as the type parameter

```java
JsonType<MyGenericPageResult> type = jsonb.type(MyGenericPageResult.class);
```
When we are using this it's effectively a `List<Object>` and when writing json it will determine the type and adapter to use at runtime.  When reading json each object will be a `LinkedHashMap` (as the generic holder of json objects).


### 2. Using it via an actual parameterized type

```java
    ParameterizedType parameterizedType = Types.newParameterizedType(MyGenericPageResult.class, Address.class);
    JsonType<MyGenericPageResult<Address>> type = jsonb.type(parameterizedType);
```

When we are using this it's effectively known to be a `List<Address>` and everything works as you'd expect.

----
Some details:

Fields that have a generic type parameter use Object as their type and have "Generic" appended to their name.
`JsonAdapter<List<Object>> listJsonAdapterGeneric;`

These fields in construction will use the Type parameter that is passed in via the constructor (param0 is a constructor argument and defaults to Object.class):
`this.listJsonAdapterGeneric = jsonb.adapter(Types.listOf(param0));`

We see 2 constructors generated now. 

We additionally see a `public static JsonAdapter.Factory` generated which handles the creation of adapters from `ParameterizedType`s.

These factories are also registered and included in the generated `GeneratedJsonComponent`.  We see:

```
@Generated
@MetaData.Factory({MyGenericHolderJsonAdapter.class, MyGenericPageResultJsonAdapter.class}) <!-- HERE, Extra 
@MetaData({... lots ...})
public class GeneratedJsonComponent implements Jsonb.GeneratedComponent {
    ...
    builder.add(MyGenericPageResultJsonAdapter.Factory);  <!-- HERE, Extra 
    ...
```

**Comment by rbygrave** [comment]
I have released `1.1-RC1` and that is on it's way to maven central.  @kevin70 can you give that a try over the next few days or so and let us know if that works as you expect?

If it's all good then I'll re-release as version `1.1`.

Thanks, Rob.

**Comment by kevin70** [comment]
Thank you. I will try to use the new version recently.

**Comment by kevin70** [comment]
Great. I have tried the `1.1-RC1` version, which can perfectly meet my needs. Now I close this issue.

**Comment by SentryMan** [comment]
This logic doesn't seem to work on records
